name: default
channels:
    - hds.sandbox
    - conda-forge
    - bioconda
    - nodefaults
dependencies:
    - python
    - pip
    - r-base
    - anndata
    - bedtools
    - bioconductor-airway
    - bioconductor-annotationhub
    - bioconductor-apeglm
    - bioconductor-batchelor
    - bioconductor-clusterexperiment
    - bioconductor-clusterprofiler
    - bioconductor-degreport
    - bioconductor-deseq2
    - bioconductor-dose
    - bioconductor-ensembldb
    - bioconductor-geneoverlap
    - bioconductor-genomeinfodb
    - bioconductor-ggtree
    - bioconductor-limma
    - bioconductor-mast
    - bioconductor-multtest
    - bioconductor-pathview
    - bioconductor-rhdf5
    - bioconductor-tximport
    - bioconductor-vsn
    - bioconductor-spatialexperiment
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-org.dm.eg.db
    - bioconductor-genomicranges
    - hds.sandbox::r-annotables
    - r-irkernel
    - nextflow
    - qualimap
    - r-cluster
    - r-clustersim
    - r-cowplot
    - r-dofuture
    - r-enrichr
    - r-factoextra
    - r-factominer
    - r-fossil
    - r-fpc
    - r-ggbeeswarm
    - r-ggnewscale
    - r-ggpubr
    - r-ggrepel
    - r-ggplot2
    - r-ggraph
    - r-ggsci
    - r-globals>=0.16.1
    - r-parallelly>=1.34.0
    - r-gprofiler2
    - r-hexbin
    - r-hdf5r
    - r-httr
    - r-igraph
    - r-irlba
    - r-irkernel
    - r-matrix
    - r-metap
    - r-nmf
    - r-patchwork
    - r-pheatmap
    - r-r.utils
    - r-rcolorbrewer
    - r-readxl
    - r-remotes
    - r-reticulate>=1.35
    - r-rfast
    - r-signac
    - r-statmod
    - r-stringi
    - r-tidyr
    - r-tidyverse
    - r-qlcmatrix
    - squidpy
    - r-magick
    - imagemagick
    - r-biocmanager
    
