---
title: "Research results RNAseq"
author: "Jose Alejandro Romero Herrera"
date: '`r Sys.Date()`'
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_format='all',
                        output_dir='../reports/')})
output:
  # To create PDF report, uncomment below
  #pdf_document:
  #  toc: yes
  html_document:
    number_sections: yes
    theme: yeti
    toc: yes
    toc_float: yes
    df_print: paged
    dev: png
---

```{r knitr, include = FALSE}
DOCNAME = knitr::current_input()
knitr::opts_chunk$set(autodep        = TRUE,
                      cache          = FALSE,
                      cache.path     = paste0("cache/", DOCNAME, "/"),
                      cache.comments = TRUE,
                      echo           = TRUE,
                      error          = FALSE,
                      fig.align      = "center",
                      fig.path       = paste0("../reports/figures/", DOCNAME, "/"),
                      fig.width      = 10,
                      fig.height     = 8,
                      message        = FALSE,
                      warning        = FALSE)
```

# Introduction

Plot for RNAseq research results in Pubmed from 2000 to 2021


# Load libraries

```{r}
library(tidyverse)
library(reshape2)
```

# Load data
```{r}
df <- read_csv("Documents/Work/HeaDS/projects/sandbox/bulk_rnaseq_course/data/PubMed_Timeline_Results_by_Year_Medicine.csv", skip = 2, col_names = c("Year","RNAseq and Medicine"))
```


```{r}
df_medicine<- read_csv("Documents/Work/HeaDS/projects/sandbox/bulk_rnaseq_course/data/PubMed_Timeline_Results_by_Year.csv", skip = 2, col_names = c("Year","RNAseq"))
```
```{r}
df <- merge(df, df_medicine, by = "Year")
head(df)
```
```{r}
df <- melt(df, id.vars = "Year")
head(df)
df$variable <- factor(df$variable, levels = c("RNAseq","RNAseq and Medicine"))
```

# Plot
```{r}
ggplot(filter(df, Year < 2021), aes(x = Year, y = value, group = variable)) + 
         geom_area(aes(fill = variable), alpha = 1, position = position_identity()) + 
         geom_line(aes()) + 
         theme_bw() + labs(y = "Number of PubMed entries with keywords", 
                           fill = "Keywords")
```


# Session info

```{r session-info, cache = FALSE}
devtools::session_info()
```
