---
title: "Default Template"
author: "Author"
date: '`r Sys.Date()`'
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_format='all',
                        output_dir='../reports/')})
output:
  # To create PDF report, uncomment below
  #pdf_document:
  #  toc: yes
  html_document:
    number_sections: yes
    theme: yeti
    toc: yes
    toc_float: yes
    df_print: paged
    dev: png
---

```{r knitr, include = FALSE}
DOCNAME = knitr::current_input()
knitr::opts_chunk$set(autodep        = TRUE,
                      cache          = FALSE,
                      cache.path     = paste0("cache/", DOCNAME, "/"),
                      cache.comments = TRUE,
                      echo           = TRUE,
                      error          = FALSE,
                      fig.align      = "center",
                      fig.path       = paste0("../reports/figures/", DOCNAME, "/"),
                      fig.width      = 10,
                      fig.height     = 8,
                      message        = FALSE,
                      warning        = FALSE)
```

# Introduction

Plots to explain data transformations on RNAseq count data

# Load libraries
```{r}
library(tidyverse)
library(DESeq2)
library(RColorBrewer)
library(pheatmap)
library(gprofiler2)
```

# Prepare data

```{r}
cts <- data.frame(read.csv(file = "../data/pasilla_cts.tsv",sep="\t",row.names="flybase_id"))
head(cts)
```

```{r}
coldata <- read.csv(file = "../data/pasilla_metadata.tsv", row.names=1, sep = "\t")
head(coldata)
```

```{r}
dds <- DESeqDataSetFromMatrix(countData = cts,
                              colData = coldata,
                              design = ~ condition)
dds
```

```{r}
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]
```

```{r}
dds <- DESeq(dds)

```

# Prepare visualizations
```{r}
melt_cts <- reshape2::melt(cts)

melt_cts$log2 <- log2(melt_cts$value + 1)

norm_cts <- data.frame(counts(dds, normalized=TRUE))

melt_norm <- reshape2::melt(norm_cts)
```


# Plots
```{r, fig.height=2, fig.width=2.5}
ggplot(melt_cts, aes(x = value, group = variable, color = variable)) + 
  geom_density() + xlab("Raw counts")
```


```{r, fig.height=2, fig.width=2.5}
ggplot(melt_cts, aes(x = log2, group = variable, color = variable)) + 
  geom_density() + xlab("log2(Raw counts + 1)")
```


```{r, fig.height=2, fig.width=2.5}
ggplot(melt_norm, aes(x = value, group = variable, color = variable)) + 
  geom_density() + xlab("Normalized counts")
```

# Session info

```{r session-info, cache = FALSE}
devtools::session_info()
```
